name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:6.2.2-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: gradle distZip
