name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:6.2.2-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Get project version
        run: echo ::set-env name=PROJECT_VERSION::$(gradle properties -q | grep "version:" | awk '{print $2}')
      - name: Build project
        run: gradle distZip
      - name: Upload distribution archive
        uses: actions/upload-artifact@v1
        with:
          name: "roguelike-${{ env.PROJECT_VERSION }}-${{ github.sha }}.zip"
          path: "build/distributions/roguelike-${{ env.PROJECT_VERSION }}.zip"
